---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是在寻找一个问题的快速答案，此常见问题解答将会有所帮助。 
---
= 有关 Cloud Data sense 的常见问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是在寻找一个问题的快速答案，此常见问题解答将会有所帮助。



== 什么是云数据的意义？

Cloud Data sense 是一款云产品，它利用人工智能（ AI ）驱动的技术帮助企业了解数据环境并识别存储系统中的敏感数据。这些系统可以是 Azure NetApp Files 配置，适用于 ONTAP 的 Amazon FSx ， Cloud Volumes ONTAP 系统（托管在 AWS ， Azure 或 GCP 中）， Amazon S3 存储分段，内部 ONTAP 系统， 非 NetApp 文件共享，通用 S3 对象存储，数据库， OneDrive 帐户和 SharePoint 帐户。

Cloud Data sense 提供了预定义的参数（例如敏感信息类型和类别），用于满足有关数据隐私和敏感度的新数据合规性法规，例如 GDPR ， CCPA ， HIPAA 等。



== 为什么要使用 Cloud Data sense ？

Cloud Data sense 可以为您提供数据，帮助您：

* 遵守数据合规性和隐私法规。
* 遵守数据保留策略。
* 根据 GDPR ， CCPA ， HIPAA 和其他数据隐私法规的要求，根据数据主题轻松查找和报告特定数据。




== Cloud Data sense 的常见用例有哪些？

* 识别个人身份信息（ PiII ）。
* 根据 GDPR 和 CCPA 隐私法规的要求确定广泛的敏感信息。
* 遵守新的和即将出台的数据隐私法规。


https://cloud.netapp.com/cloud-compliance["详细了解 Cloud Data sense 的用例"^]。



== 可以使用 Cloud Data sense 扫描哪些类型的数据？

云数据感知支持通过 NFS 和 CIFS 协议扫描非结构化数据，这些协议由 Cloud Volumes ONTAP ， Azure NetApp Files ， Amazon FSx for ONTAP ，内部 ONTAP 系统以及非 NetApp 文件共享管理。Data sense 支持 NFS 3.x ， 4.0 和 4.1 以及 CIFS 1.x ， 2.0 ， 2.1 和 3.0 版。

Data sense 还可以扫描存储在 Amazon S3 存储分段和通用 S3 对象存储中的数据。

此外， Data sense 还可以扫描位于任何位置的数据库以及 OneDrive 和 SharePoint 帐户中的用户文件。

link:concept-cloud-compliance.html#how-scans-work["了解扫描的工作原理"^]。



== 支持哪些云提供商？

Cloud Data sense 作为 Cloud Manager 的一部分运行，并支持 AWS ， Azure 和 GCP 。这样，您的组织就可以在不同的云提供商之间实现统一的隐私可见性。



== 如何访问 Cloud Data sense ？

Cloud Data sense 通过 Cloud Manager 进行操作和管理。您可以从 Cloud Manager 中的 * 数据感知 * 选项卡访问数据感知功能。



== 云数据感知的工作原理是什么？

Cloud Data sense 可在 Cloud Manager 系统和存储系统的同时部署另一层人工智能。然后，它会扫描卷，分段，数据库和 OneDrive 帐户上的数据，并为找到的数据洞察力编制索引。

link:concept-cloud-compliance.html["详细了解 Cloud Data sense 的工作原理"^]。



== 云数据的成本有多高？

使用 Cloud Data sense 的成本取决于您要扫描的数据量。Data sense 在 Cloud Manager 工作空间中扫描的前 1 TB 数据是免费的。要在这之后继续扫描数据，需要订阅 AWS ， Azure 或 GCP Marketplace 或 NetApp 提供的 BYOL 许可证。请参见 https://cloud.netapp.com/netapp-cloud-data-sense#Pricing["定价"^] 了解详细信息。



== 云数据感知需要哪种类型的实例或虚拟机？

时间 link:task-deploy-cloud-compliance.html["部署在云中"]：

* 在 AWS 中， Cloud Data sense 在具有 500 GB GP2 磁盘的 m5.4xlarge 实例上运行。
* 在 Azure 中， Cloud Data sense 在具有 512 GB 磁盘的 Standard_d16s_v3 VM 上运行。
* 在 GCP 中， Cloud Data sense 在具有 512 GB 标准永久性磁盘的 n2-standard-16 VM 上运行。


您可以在可通过网络或云访问 Internet 的 Linux 主机上安装 Data sense 软件。所有功能均相同，您可以继续通过 Cloud Manager 管理扫描配置和结果。请参见 link:task-deploy-compliance-onprem.html["在内部部署 Cloud Data sense"] 了解系统要求和安装详细信息。

此外，您还可以 link:task-deploy-compliance-dark-site.html["在无法访问 Internet 的内部站点中部署 Data sense"] 适用于完全安全的站点。

请注意，您可以在 CPU 较少且 RAM 较少的系统上部署 Data sense ，但使用这些系统时会有一些限制。请参见 link:concept-cloud-compliance.html#using-a-smaller-instance-type["使用较小的实例类型"] 了解详细信息。

link:concept-cloud-compliance.html["详细了解 Cloud Data sense 的工作原理"^]。



== Cloud Data sense 扫描我的数据的频率如何？

数据经常发生变化，因此 Cloud Data sense 可以持续扫描数据，而不会对数据造成影响。虽然数据的初始扫描可能需要较长时间，但后续扫描只会扫描增量更改，从而缩短系统扫描时间。

link:concept-cloud-compliance.html#how-scans-work["了解扫描的工作原理"]。

数据扫描对存储系统和数据的影响可以忽略不计。但是，如果您担心即使影响很小，也可以将 Data sense 配置为执行 " 缓慢 " 扫描。 link:task-managing-compliance.html#reducing-the-data-sense-scan-speed["请参见如何降低扫描速度"]。



== Cloud Data sense 是否提供报告？

是的。Cloud Data sense 提供的信息可能与您组织中的其他利益相关方相关，因此我们可以帮助您生成报告以分享这些见解。

以下报告可用于 Data sense ：

隐私风险评估报告:: 根据您的数据提供隐私洞察力并获得隐私风险得分。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["了解更多信息。"^]。
数据主体访问请求报告:: 用于提取包含数据主体的特定名称或个人标识符相关信息的所有文件的报告。 link:task-responding-to-dsar.html["了解更多信息。"^]。
PCI DSS 报告:: 帮助您确定信用卡信息在整个文件中的分布情况。 link:task-generating-compliance-reports.html#pci-dss-report["了解更多信息。"^]。
HIPAA 报告:: 帮助您确定运行状况信息在文件中的分布情况。 link:task-generating-compliance-reports.html#hipaa-report["了解更多信息。"^]。
数据映射报告:: 提供有关工作环境中文件大小和数量的信息。其中包括使用容量，数据期限，数据大小和文件类型。 link:task-generating-compliance-reports.html#data-mapping-report["了解更多信息。"^]。
报告特定信息类型:: 我们提供的报告包含有关包含个人数据和敏感个人数据的已识别文件的详细信息。您还可以查看按类别和文件类型细分的文件。 link:task-controlling-private-data.html["了解更多信息。"^]。




== 扫描性能是否有所不同？

扫描性能可能因网络带宽和环境中的平均文件大小而异。它还可能取决于主机系统（在云端或内部）的大小特征。请参见 link:concept-cloud-compliance.html#the-cloud-data-sense-instance["云数据感知实例"] 和 link:task-deploy-cloud-compliance.html["部署 Cloud Data sense"] 有关详细信息 ...

在首次添加新数据源时，您还可以选择仅执行 " 映射 " 扫描，而不是执行完整的 " 分类 " 扫描。由于无法访问文件以查看数据源中的数据，因此可以非常快速地对数据源进行映射。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["查看映射扫描与分类扫描之间的区别。"]



== 支持哪些文件类型？

Cloud Data sense 会扫描所有文件以获取类别和元数据洞察力，并在信息板的文件类型部分显示所有文件类型。

当 Data sense 检测到个人身份信息（ Pii ）或执行 DSAL 搜索时，仅支持以下文件格式： .CSV ， .dcm ， .DICOM、 .DOC ， .docx ， .json ， .PDF ， .PPTX ， .RTV ， .TXT ， .XLS 和 .XLSX 。



== 如何启用 Cloud Data sense ？

首先，您需要在 Cloud Manager 中部署 Cloud Data sense 实例。实例运行后，您可以从 * 数据感知 * 选项卡或通过选择特定的工作环境在现有工作环境和数据库上启用此服务。

link:task-getting-started-compliance.html["了解如何开始使用"^]。


NOTE: 激活 Cloud Data sense 可立即执行初始扫描。扫描结果会在之后不久显示。



== 如何禁用 Cloud Data sense ？

您可以从 " 数据感知配置 " 页面禁用 Cloud Data sense 扫描单个工作环境，数据库，文件共享组， OneDrive 帐户或 SharePoint 帐户。

link:task-managing-compliance.html["了解更多信息。"^]。


NOTE: 要完全删除 Cloud Data sense 实例，您可以从云提供商的门户或内部位置手动删除 Data sense 实例。



== 如果在 ONTAP 卷上启用了数据分层，会发生什么情况？

您可能希望在将冷数据分层到对象存储的 ONTAP 系统上启用云数据感知。如果启用了数据分层，则 Data sense 会扫描所有数据—磁盘上的数据以及分层到对象存储的冷数据。

合规性扫描不会加热冷数据，它会保持冷数据并分层到对象存储。



== 是否可以使用云数据感知扫描内部 ONTAP 存储？

是的。只要您在 Cloud Manager 中发现内部 ONTAP 集群是一个工作环境，就可以扫描卷数据。



== Cloud Data sense 能否向我的组织发送通知？

是的。通过与策略功能结合使用，您可以在策略返回结果时向 Cloud Manager 用户发送电子邮件警报（每日，每周或每月），以便您可以收到保护数据的通知。了解更多信息 link:task-org-private-data.html#controlling-your-data-using-policies["策略"^]。

您还可以从 " 监管 " 页面和 " 调查 " 页面下载状态报告，并在组织内部共享这些报告。



== 我是否可以根据组织的需求自定义服务？

Cloud Data sense 提供对数据的即装即用洞察力。您可以根据组织的需求提取和利用这些洞察信息。

此外，您还可以使用 * 数据检测 * 功能让 Fusion 根据您正在扫描的数据库中特定列中的标准扫描所有数据，这实际上使您可以创建自己的自定义个人数据类型。

link:task-managing-data-fusion.html#creating-custom-personal-data-identifiers-from-your-databases["了解更多信息。"^]。



== Cloud Data sense 是否可以与我的文件中嵌入的 AIP 标签配合使用？

是的。如果您已订阅，则可以管理 Cloud Data sense 正在扫描的文件中的 AIP 标签 link:https://azure.microsoft.com/en-us/services/information-protection/["Azure 信息保护（ AIP ）"^]。您可以查看已分配给文件的标签，向文件添加标签以及更改现有标签。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["了解更多信息。"^]。



== 是否可以将云数据感知信息限制为特定用户？

是的， Cloud Data sense 已与 Cloud Manager 完全集成。Cloud Manager 用户只能根据其工作空间权限查看其有资格查看的工作环境的信息。

此外，如果您希望允许某些用户只查看数据感知扫描结果而不能管理数据感知设置，则可以为这些用户分配 _Cloud Compliance Viewer_ 角色。

link:concept-cloud-compliance.html#user-access-to-compliance-information["了解更多信息。"^]。
