---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Cloud Data sense可以在您的卷、Amazon S3存储分段、数据库、OneDrive文件夹、SharePoint帐户中识别多种类型的私有数据。 和Google Drive帐户。 
---
= 私有数据的类别
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Data sense可以在您的卷、Amazon S3存储分段、数据库、OneDrive文件夹、SharePoint帐户中识别多种类型的私有数据。 和Google Drive帐户。请参见以下类别。


TIP: 如果您需要 Cloud Data sense 识别其他私有数据类型，例如其他国家 / 地区 ID 号或医疗保健标识符，请根据您的请求向 ng-contact-data-sense@netapp.com 发送电子邮件。



== 个人数据的类型

文件中的个人数据可以是常规个人数据或国家标识符。第三列标识 Cloud Data sense 是否使用 link:task-controlling-private-data.html#viewing-files-that-contain-personal-data["接近验证"^] 以验证其对标识符的发现。

可以使用任何语言识别此类别中的项目。

请注意，如果要扫描数据库服务器，您可以将这些数据添加到文件中的个人数据列表中。Data DataSIF_ 功能允许您通过选择数据库表中的列来选择 Fusion sense 在其扫描中查找的其他标识符。请参见 link:task-managing-data-fusion.html["使用 Data Fusion 添加个人数据标识符"^] 了解详细信息。

[cols="20,50,18"]
|===
| Type | 标识符 | 是否进行接近验证？ 


.5+| 常规 | 电子邮件地址 | 否 


| 信用卡号 | 否 


| IBAN 编号（国际银行帐号） | 否 


| IP 地址 | 否 


| Password | 是的。 


.45+| 国家标识符 | 澳大利亚 TFN （税务文件编号） | 是的。 


| 澳大利亚驱动程序许可证编号 | 是的。 


| 澳大利亚医疗保健计划编号 | 是的。 


| 澳大利亚护照编号 | 是的。 


| 奥地利 SSN | 是的。 


| 比利时 ID （ Numero National ） | 是的。 


| 巴西 ID （ CPF ） | 是的。 


| 英国护照 | 是的。 


| Bulgarian" ID （ UCN ） | 是的。 


| 加利福尼亚驾驶执照 | 是的。 


| 克罗地亚语 ID （ OIB ） | 是的。 


| 塞浦路斯税务识别号（ TIC ） | 是的。 


| 捷克语 / 斯洛伐克语 ID | 是的。 


| 丹麦语 ID （常驻代表） | 是的。 


| 荷兰语 ID （ BSN ） | 是的。 


| 爱沙尼亚语 ID | 是的。 


| 芬兰语 ID （ HETU ） | 是的。 


| 法语版驱动程序许可证 | 是的。 


| 法语 ID | 是的。 


| 法语 INSEE | 是的。 


| 法语社会保障号码 | 是的。 


| 法国税务识别号（ SPI ） | 是的。 


| 德国税务识别号（ Steuerliche Identifikationsnummer ） | 是的。 


| 希族 ID | 是的。 


| 匈牙利税务标识号 | 是的。 


| 印第安纳驾驶执照 | 是的。 


| 爱尔兰 ID （ PPs ） | 是的。 


| 以色列 ID | 是的。 


| 意大利税务标识号 | 是的。 


| Latvian ID | 是的。 


| 立陶宛语 ID | 是的。 


| 卢森堡 ID | 是的。 


| 马耳他 ID | 是的。 


| 国家卫生服务（ NHS ）编号 | 是的。 


| 纽约驾驶执照 | 是的。 


| 波兰语 ID （ PESEL ） | 是的。 


| 葡萄牙税务识别号（ NIF ） | 是的。 


| 罗马尼亚语 ID （ CNP ） | 是的。 


| 斯洛文尼亚语 ID （ EMO ） | 是的。 


| 南非 ID | 是的。 


| 西班牙语税务标识号 | 是的。 


| 瑞典语 ID | 是的。 


| 德克萨斯驱动程序许可证 | 是的。 


| 英国ID （ Nino ） | 是的。 


| 美国社会保险号（ SSN ） | 是的。 
|===


== 敏感个人数据的类型

Cloud Data sense 可在文件中找到的敏感个人数据包括以下列表。目前，此类别中的项目只能识别为英语。

《刑事诉讼参考》:: 有关自然人的犯罪和犯罪的数据。
《种族参考》:: 与自然人的种族或种族有关的数据。
运行状况参考:: 有关自然人健康的数据。
ICD-9-CM 医疗代码:: 医疗和健康行业使用的代码。
ICD-10-CM 医疗代码:: 医疗和健康行业使用的代码。
《理念参考》:: 与自然人的理念相关的数据。
《政治观点参考》:: 与自然人的政治观点相关的数据。
《宗教信仰参考》:: 有关自然人的宗教信仰的数据。
性寿命或方向参考:: 有关自然人的性生活或性取向的数据。




== 类别类型

Cloud Data sense 可按如下方式对数据进行分类：其中大多数类别均可获得英语，德语和西班牙语的认可。

[cols="25,25,15,15,15"]
|===
| 类别 | Type | 英语 | 德语 | 西班牙语 


.4+| 财务 | 资产负债表 | ✓ | ✓ | ✓ 


| 采购订单 | ✓ | ✓ | ✓ 


| 发票 | ✓ | ✓ | ✓ 


| 季度报告 | ✓ | ✓ | ✓ 


.6+| 人力资源 | 后台检查 | ✓ |  | ✓ 


| 薪酬计划 | ✓ | ✓ | ✓ 


| 员工合同 | ✓ |  | ✓ 


| 员工审核 | ✓ |  | ✓ 


| 运行状况 | ✓ |  | ✓ 


| 恢复 | ✓ | ✓ | ✓ 


.2+| 法律 | NDAS | ✓ | ✓ | ✓ 


| 供应商 - 客户合同 | ✓ | ✓ | ✓ 


.2+| 营销 | 营销活动 | ✓ | ✓ | ✓ 


| 会议 | ✓ | ✓ | ✓ 


| 操作 | 审核报告 | ✓ | ✓ | ✓ 


| 销售 | 销售订单 | ✓ | ✓ |  


.4+| 服务 | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| SOW | ✓ | ✓ | ✓ 


| 培训 | ✓ | ✓ | ✓ 


| 支持 | 投诉和服务单 | ✓ | ✓ | ✓ 
|===
此外，还会对以下元数据进行分类，并使用相同的受支持语言进行标识：

* 应用程序数据
* 归档文件
* 音频
* 业务应用程序数据
* CAD 文件
* 代码
* 已损坏
* 数据库和索引文件
* 设计文件
* 通过电子邮件发送应用程序数据
* Encrypted
* 可执行文件
* 财务应用程序数据
* 运行状况应用程序数据
* 映像
* 日志
* 其他文档
* 其他演示文稿
* 其他电子表格
* 其他 " 未知 "
* 结构化数据
* 视频
* 零字节文件




== 文件类型

Cloud Data sense 会扫描所有文件以获取类别和元数据洞察力，并在信息板的文件类型部分显示所有文件类型。

但是，当 Data sense 检测到个人可识别信息（ PiD ）或执行 DSAL 搜索时，仅支持以下文件格式：

`+.CSV、.dcm、.Dicom、.DOC、.docx、 .json、.PDF、.PPTX、.RTV、.TXT、 .XLS、.XLSX、文档、工作表和幻灯片+`



== 发现的信息准确性

NetApp 无法保证 Cloud Data sense 识别的个人数据和敏感个人数据的 100% 准确性。您应始终通过查看数据来验证此信息。

根据我们的测试，下表显示了 Data sense 所发现的信息的准确性。我们将其细分为 _precis度 _ 和 _recall_ ：

精确度:: 正确识别数据感知所发现的可能性。例如，个人数据的精确率为 90% 意味着，在被确定包含个人信息的 10 个文件中，有 9 个文件实际上包含个人信息。每 10 个文件中就有 1 个是误报文件。
重新调用:: 数据感知找到应做之事的可能性。例如，个人数据的重新调用率为 70% ，这意味着 Data sense 可以识别贵组织中实际包含个人信息的 10 个文件中的 7 个文件。数据感知可能会丢失 30% 的数据，并且不会显示在信息板中。


我们不断提高结果的准确性。这些改进功能将在未来的 Data sense 版本中自动提供。

[cols="25,20,20"]
|===
| Type | 精确度 | 重新调用 


| 个人数据—常规 | 90% 到 95% | 60%-80% 


| 个人数据—国家 / 地区标识符 | 30% 到 60% | 40%-60% 


| 敏感的个人数据 | 80%-95% | 20%-30% 


| 类别 | 90% 到 97% | 60%-80% 
|===