---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 了解 Cloud Data sense 中的新增功能。 
---
= Cloud Data sense 的新增功能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 Cloud Data sense 中的新增功能。



== 2022 年 4 月 5 日



=== Data sense 可以识别四种新类型的澳大利亚个人数据

Data sense 可以识别包含澳大利亚 TFN （税务文件编号），澳大利亚驾驶执照编号，澳大利亚医疗保健服务编号和澳大利亚护照编号的文件并对其进行分类。 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 现在，全局 Active Directory 服务器可以是 LDAP 服务器

与 Data sense 集成的全局 Active Directory 服务器现在可以是 LDAP 服务器，而不是以前支持的 DNS 服务器。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-add-active-directory-datasense.html["有关详细信息，请访问此处"]。



== 2022 年 3 月 15 日



=== 新筛选器可显示特定用户或组具有读取或写入权限的文件

添加了一个名为 " 用户 / 组权限 " 的新筛选器，您可以列出特定用户或组具有读取和 / 或写入权限的文件。您可以指定用户名或组名称，也可以指定部分名称。此功能适用于 Cloud Volumes ONTAP ，内部 ONTAP ， Azure NetApp Files ，适用于 ONTAP 的 Amazon FSx 和文件共享上的卷。



=== Data sense 可以确定 SharePoint 和 OneDrive 帐户中文件的权限

Data sense 现在可以读取 OneDrive 帐户和 SharePoint 帐户中正在扫描的文件的权限。此信息显示在 " 调查 " 窗格中的文件详细信息以及 " 监管信息板 " 中的 " 打开权限 " 区域中。



=== Data sense 还可以识别另外两种类型的个人数据

* 法语 INSEE — INSEE 代码是法国国家统计和经济研究所（ INSEE ）用来标识各种实体的数字代码。
* 密码—此信息通过查找字母数字字符串旁边的 "password" 一词的组合来使用接近验证来标识。找到的项目数将在合规性信息板的 " 个人结果 " 下列出。您可以使用筛选器 * 个人数据 > 密码 * 在调查窗格中搜索包含密码的文件。




=== 支持在非公开站点中部署时扫描 OneDrive 和 SharePoint 数据

如果您已在无法访问 Internet 的内部站点中的主机上部署 Cloud Data sense ，则现在可以从 OneDrive 帐户或 SharePoint 帐户扫描本地数据。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-dark-site.html#sharepoint_and_onedrive_special_requirements["您需要允许访问以下端点。"]



=== 此版本已停止使用 Cloud Data sense 扫描 Cloud Backup 文件的测试版功能



== 2022 年 2 月 9 日



=== 增加了对扫描 Microsoft SharePoint 联机帐户的支持

现在，您可以将 SharePoint 联机帐户添加到 Data sense 中，以便扫描 SharePoint 站点中的文档和文件。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html["了解如何扫描 SharePoint 帐户"]。



=== Data sense 可以将文件从数据源复制到目标位置，并同步这些文件

如果您要迁移数据，并且希望捕获最近对文件所做的任何更改，则此功能非常有用。此操作将使用 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync"^] 用于将数据从源复制并同步到目标的功能。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["请参见如何复制和同步文件"]。



=== 为 DAR 报告提供了新的语言支持

现在，在搜索数据主体名称以创建数据主体访问请求（ Data Subject Access Request ， DSAar ）报告时，支持德语和西班牙语。本报告旨在帮助贵组织满足 GDPR 或类似数据隐私法律的要求。



=== Data sense 可识别另外三种类型的个人数据

Data sense 现在可以在文件中找到法语社会安全号码，法语 ID 和法语驱动程序许可证号码。 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["查看 Data sense 在扫描中标识的所有个人数据类型的列表"]。



=== 已更改安全组端口，以便与连接器进行数据感知通信

Cloud Manager Connector 的安全组将使用端口 443 而非端口 80 来处理传入和传出 Data sense 实例的入站和出站流量，以提高安全性。此时，这两个端口都保持打开状态，因此您不应看到任何问题，但您应在任何早期的 Connector 部署中更新安全组，因为端口 80 将在未来版本中弃用。



== 2022 年 1 月 2 日



=== 能够集成全局 Active Directory 以确定文件所有者和权限

现在，您可以将全局 Active Directory 与 Cloud Data sense 集成在一起，以增强 Data sense 报告的有关文件所有者以及哪些用户和组有权访问您的文件的结果。

除了您输入 Active Directory 凭据以使 Data sense 能够从某些数据源扫描 CIFS 卷之外，此新集成还为其他用户和系统提供了额外的集成。Data sense 将在所有集成的 Active Directory 中查找用户和权限详细信息。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-add-active-directory-datasense.html["请参见如何设置全局 Active Directory"]。



=== 现在，可以使用数据感知 " 策略 " 删除文件

Data sense 可以自动删除与策略中定义的查询匹配的文件。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#deleting-source-files-automatically-using-policies["请参见如何创建自定义策略"]。



== 2021 年 12 月 16 日



=== 数据感知功能可以扫描非公开站点中的数据

Cloud Manager （ Connector ）和 Cloud Data sense 均可部署在无法访问 Internet 的内部站点中。现在，您的安全站点可以使用 Cloud Manager 管理内部 ONTAP 集群，在集群之间复制数据，以及使用 Cloud Data sense 扫描这些集群中的数据。

link:task-deploy-compliance-dark-site.html["了解如何在无法访问 Internet 的站点中部署 Cloud Data sense"^]。



== 2021 年 11 月 28 日



=== 数据感知可用于从 ONTAP 系统克隆卷

您可以使用 Data sense 克隆 ONTAP 卷，但在新克隆的卷中只包含源卷中的选定文件。如果您要迁移数据并希望排除某些文件，或者要创建卷的副本以供测试，则此功能非常有用。

link:task-managing-highlights.html#cloning-volume-data-to-a-new-volume["请参见如何克隆卷"]。



=== 现在， Cloud Manager 的 GCP Marketplace 订阅支持 Cloud Data sense

。 https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project&rif_reserved["Cloud Manager 的 GCP Marketplace 订阅"^] 现在支持 Cloud Data sense 。现在，除了使用 NetApp 的 BYOL 许可证之外，您还可以使用此按需购买（ PAYGO ）订阅从部署在 Google Cloud 存储上的 Cloud Volumes ONTAP 系统扫描数据。



=== 能够查看长期运行的合规性操作的状态

从调查结果窗格对多个文件运行操作时，例如删除 50 个文件，此过程可能需要一些时间。现在，您可以监控这些异步操作的状态，以便了解它何时应用于所有文件。

link:task-managing-highlights.html#viewing-the-status-of-your-compliance-actions["了解如何查看持续合规操作的状态"]。



=== Data sense 还可以识别另外两种类型的个人数据

Data sense 现在可以在文件中找到个人数据类型 " 英国护照 " 和 " 国家卫生服务（ NHS ）编号 " 。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 在扫描中发现的所有个人数据类型的列表"]。



=== 新的筛选器可显示属于特定工作环境类型的文件

在 " 数据调查 " 页面中筛选数据时，为 " 工作环境类型 " 添加了一个新的筛选器。这样，您可以筛选 Cloud Volumes ONTAP 系统，适用于 ONTAP 系统的 FSX ，内部 ONTAP 系统等的结果。



== 2021 年 11 月 7 日



=== 现在，您可以选择对工作环境中的各个卷进行映射或分类

过去，您可以映射所有卷，也可以映射并分类每个工作环境中的所有卷。现在，您可以选择映射 _or_ 映射各个卷并对其进行分类。此选项适用于 Cloud Volumes ONTAP 卷， ANF 卷，内部 ONTAP 卷以及 ONTAP 卷的 FSX 。



=== 数据感知可以将文件从数据源复制到目标 NFS 共享

您可以将 Data sense 正在扫描的任何源文件复制到目标 NFS 共享。如果要为某些数据创建副本并将其移动到其他 NFS 位置，此功能将非常有用。 link:task-managing-highlights.html#copying-source-files-to-an-nfs-share["了解更多信息。"]。



=== 可以扫描 ONTAP 文件系统的 FSX 上的数据保护卷

现在，您可以在 ONTAP 文件系统的 FSX 上扫描数据保护卷。 link:task-scanning-fsx.html#scanning-data-protection-volumes["了解更多信息。"]。



=== 新的筛选器可按 Data sense 首次发现文件时的日期范围显示文件

通过 " 调查 " 页面中的一个名为 " 发现时间 " 的新筛选器，您可以按 Data sense 首次发现文件时的日期范围查看文件。发现的时间也已添加到 " 文件详细信息 " 页面以及以 CSV 格式为文件输出的报告中。



=== SOC 2 类型 2 认证

一家独立的认证公有 会计师事务所和服务审计师对云数据感知进行了检查，并确认它已根据适用的信任服务标准获得 SOC 2 类型 2 报告。

https://www.netapp.com/company/trust-center/compliance/soc-2/["查看 NetApp 的 SOC 2 报告"^]。



== 2021 年 10 月 4 日



=== 支持 NetApp 的 BYOL 许可

除了通过云提供商市场许可 Data sense 之外，现在您还可以从 NetApp 购买自带许可证（ BYOL ），该许可证可用于所有工作环境和 Cloud Manager 帐户中的数据源。

link:task-licensing-datasense.html#use-a-cloud-data-sense-byol-license["了解有关全新 Cloud Data sense BYOL 许可证的更多信息"]。



=== 支持 Google Cloud Platform

现在， Cloud Data sense 可以扫描部署在 GCP 上的 Cloud Volumes ONTAP 系统中的数据。数据感知必须部署在 GCP 上，而连接器必须部署在 GCP 或内部环境中。与 Connector 关联的 GCP 服务帐户需要最新权限才能将 Cloud Data sense 部署到 GCP 。



=== 可以在 ONTAP 文件系统的 FSX 上扫描 CIFS 卷

现在， Data sense 可以从 ONTAP 系统的 FSX 扫描 CIFS 卷。 link:task-scanning-fsx.html["请参见如何扫描 Amazon FSX 中的 ONTAP 卷"]。



== 2021 年 9 月 2 日



=== 可以在 ONTAP 文件系统的 FSX 上扫描 NFS 卷

增加了对在适用于 ONTAP 系统的 Amazon FSX 上扫描 NFS 卷上数据的支持。 link:task-scanning-fsx.html["请参见如何为适用于 ONTAP 的 FSX 系统配置扫描"]。



=== 数据感知 " 状态 " 条目已更改为 " 标记 " 条目

使用 Data sense 向文件添加 " 状态 " 信息的功能已将术语更改为 " 标记 " 。这些标记是文件级标记，请勿与可应用于卷， EC2 实例，虚拟机等的资源级标记相混淆 link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["了解有关文件级标记的更多信息"]。



== 2021 年 8 月 1 日



=== 一次可管理多个文件的文件设置

在早期版本的 Cloud Data sense 中，您可以一次对一个文件执行以下操作：添加状态标记，分配用户和添加 AIP 标签。现在，您可以从 " 数据调查 " 页面中选择多个文件，并对多个文件执行其中每个操作。



=== " 监管 " 信息板可显示数据的创建时间或上次访问时间

在 " 监管 " 信息板中查看 " 数据期限 " 图时，除了根据上次修改时间查看数据之外，现在您还可以按数据创建时间或上次访问时间（读取时）查看数据。此信息也会在数据映射报告中提供。



=== 扫描大型配置时，可以使用多个主机提高处理能力

在内部部署 Data sense 时，如果您计划扫描包含 PB 数据的配置，现在可以在其他内部主机上安装扫描软件。在扫描非常大的配置时，这些额外的 _scanner nodes_ 可提高处理能力。

请参见操作说明 link:task-deploy-compliance-onprem.html#multi-host-installation-for-large-configurations["在多个主机上部署 Data sense 软件"]。



== 2021 年 7 月 7 日



=== 数据感知可以将文件从数据源移动到目标 NFS 共享

通过一项新功能，您可以实现 link:task-managing-highlights.html#moving-source-files-to-an-nfs-share["将 Data sense 正在扫描的任何源文件移动到任何 NFS 共享"]。这样，您可以将敏感或与安全相关的文件移动到特定区域，以便进行更多分析。



=== 能够快速对数据进行分类，而不是执行完整的分类扫描

现在，您可以选择快速将数据映射到类别中，而不是执行完整的分类扫描。这样，您就可以了 link:task-generating-compliance-reports.html#data-mapping-report["查看数据映射报告"] 从 " 监管信息板 " 中查看您的数据概览，了解您不需要对某些数据源运行完整扫描的情况。



=== 能够将文件分配给 Cloud Manager 用户

现在可以了 link:task-org-private-data.html#assigning-users-to-manage-certain-files["将文件分配给特定 Cloud Manager 用户"] 这样，该人员就可以负责对文件执行任何后续操作。此功能可与现有功能结合使用，以便向文件添加自定义标记。

通过 " 调查 " 页面中的新筛选器，您还可以轻松查看 " 已分配给 " 字段中具有相同人员的所有文件。



=== 能够使用较小的 Cloud Data sense 实例

一些扫描要求较低的用户要求能够使用较小的 Cloud Data sense 实例。现在可以了。因此，使用这些较小实例时存在一些限制 link:concept-cloud-compliance.html#using-a-smaller-instance-type["请先了解这些限制"]。



=== 能够执行慢速扫描

数据扫描对存储系统和数据的影响可以忽略不计。但是，如果您担心即使影响很小，也可以将 Data sense 配置为立即执行 " 缓慢 " 扫描。 link:task-managing-compliance.html#reducing-the-data-sense-scan-speed["了解如何操作"]。



=== 数据感知可跟踪上次访问文件的时间

上次访问时间值已添加到 " 文件详细信息 " 页面以及以 CSV 格式输出的报告中，以便您可以查看用户上次访问文件的时间。



== 2021 年 6 月 7 日



=== Cloud Compliance 已重命名为 Cloud Data sense 。

自此版本起， Cloud Compliance 已重命名为 * 云数据感知 * 。由于该产品中包含了所有新的监管功能和其他功能，因此合规性名称并不能推广所有功能。



=== " 监管信息板 " 提供了新的 " 完整数据映射 " 报告

" 监管信息板 " 提供了一份全新的 _Full Data Mapping_ 报告，用于概述企业数据源中存储的数据，以帮助您确定迁移，备份，安全性和合规性流程。

此报告提供了概述页面，其中汇总了您的所有工作环境和数据源，然后提供了每个工作环境的细分信息。 link:task-generating-compliance-reports.html#generating-the-data-mapping-report["请单击此处"] 有关详细信息：



=== 在 " 调查 " 页面中添加了新筛选器，用于查看所有重复的文件

通过 " 数据调查 " 页面中的新筛选器，您可以查看在存储系统中复制的所有文件的列表。这有助于确定可以节省存储空间的区域，或者确定具有特定权限或不希望在存储中复制的敏感信息的文件。 link:task-controlling-private-data.html#viewing-all-duplicated-files["请参见如何查看所有重复的文件"]。



=== Data sense 可以为组织的文件添加自定义标记

您可以向 Data sense 正在扫描的文件添加自定义标记。此标记与添加 AIP 标签的方式不同。Cloud Manager 用户只能看到此标记，因此您可以指示文件是否需要删除或出于某种原因进行检查。 link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["了解如何在文件中应用和查看标记"]。

通过 " 调查 " 页面中的新筛选器，您可以轻松查看已分配标记的所有文件。



=== 可以扫描 .dcm 和 .Dicom 文件

Cloud Data sense 可以在两种其他类型的文件中扫描个人身份信息（ Personal identifiable Information ， Pii ）： .dcm 和 .Dicom 。



=== Data sense 现在可跟踪文件的其他属性

已将 " 文件大小 " ， " 创建日期 " 和 " 上次修改日期 " 值添加到以 CSV 格式输出的报告中。创建日期也是一个新筛选器，可用于缩小调查页面搜索结果的范围。



== 2021 年 5 月 5 日



=== 能够扫描存储在 Azure Blob 上的数据

现在，使用时支持扫描存储在 Azure Blob 上的数据 https://min.io/["MinIO 服务"^]。请参见 link:task-scanning-object-storage.html["扫描使用 S3 协议的对象存储"] 了解详细信息。



=== 其他类型的个人数据可通过 Data sense 来识别

Cloud Data sense 现在可以在文件中找到奥地利的 SSN 。
